### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by bommezijn** [SamSlotemaker/web-app-from-scratch-2021#1]
# Peer Review 1

## Repo
**Is er een repo beschrijving?**
Een oude beschrijving van de geforkte repo.  Dit kan je leuk gebruiken voor een korte beschrijving wat de applicatie uiteindelijk zal doen.

**Is de repo open voor issues?**
Anders zal ik hier niet zien.

**Heeft het een gitignore?**
Yes, voor ```nodes.md```.

**Is het concept beschreven in de readme?**
Nope. Readme heeft nog informatie over het vak. Dit mag nog worden vervangen 😄 
_update:_ Readme bevat nu alleen een beschrijving over het vak.

**API beschreven in de readme**
Nope. Readme heeft nog informatie over het vak. Dit mag nog worden vervangen 😄 

**Live demo**
✅   Yes

Live demo is netjes gestructeerd en heeft al een responsive aspect tot zich.

## Code
**Code flow**
✅   Code is netjes opgesplitst in modules.
✅   Code is DRY geschreven.
✅   camelCase geschreven.
✅   Consistent indentation.

Variabelen zijn duidelijk benoemd en versterken de code flow & readability.
- [```oderedBy``` mist een 'r' I think?](https://github.com/SamSlotemaker/web-app-from-scratch-2021/blob/aac4e4a2933a9fd5c18bf59733a3393de270440c/js/modules/platformList.js#L2)

**Best practices voor WAFS**
script-tag staat in de ```<head>```, volgens de best practices voor WAFS willen ze dit bij de closing tag van de body.

**Global scope schoon houden**
- ✅  Global scope is niet bevuild met onnodige global declarations.

## Opmerkingen

Goed en netjes begin voor week 1.
Enige puntje dat er realistisch gezien is, is de readme een beetje opleuken met eigen informatie. Niks op te merken over de code, Leest al lekker door het splitsen in modules per individuele categorie.

**Comment by SamSlotemaker** [comment]
Will fix Readme
Will fix taalfout
Will fix scripttag
