### ISSUE TITLE
Add short-circuiting here for less verbose code?

### ISSUE THREAD

**Issue by joostf** [SamSlotemaker/web-app-from-scratch-2021#12]
https://github.com/SamSlotemaker/web-app-from-scratch-2021/blob/02180caa7be83b1d907037177a71e707dc119ab8/src/js/modules/api.js#L5-L10

https://javascript.info/logical-operators

This is a could have ;-)

**Comment by SamSlotemaker** [comment]
Fixed (denk ik?) :)  
```
    response = query ? await fetch(baseURL + subject + query) : await fetch(baseURL + subject)

```

**Comment by joostf** [comment]
A ternary is also nice option, although I would use it to build an url string first, and fetch on a new line 

Something like this could work as well:

```
const   baseUrl = 'https://github.com/',
        subject = 'SamSlotemaker'

let url = baseUrl + subject,
    repo = '/test'

!repo || (url +=  repo)
 
response = await fetch(url)
```

**Comment by SamSlotemaker** [comment]
Ah, got it, thanks :) 
```js
 let url = baseURL + subject
    !query || (url += query)

    const response = await fetch(url)
```

**Comment by joostf** [comment]
This is not the best code perse, choose coding style you like best! 
Nothing wrong with a good old fashioned if statement ;-)
