### ISSUE TITLE
Routie can be exposed as a module, no need to include it through a script element

### ISSUE THREAD

**Issue by joostf** [SamSlotemaker/web-app-from-scratch-2021#13]
https://github.com/SamSlotemaker/web-app-from-scratch-2021/blob/02180caa7be83b1d907037177a71e707dc119ab8/index.html#L17

**Comment by SamSlotemaker** [comment]
fixed

**Comment by joostf** [comment]
Also modules are deferred by default making it safe to include it in the head setion..
