### ISSUE TITLE
Peer review web-app-from-scratch-2021 week 2

### ISSUE THREAD

**Issue by ofahchouch-gh** [SamSlotemaker/web-app-from-scratch-2021#9]
**Over de readme**
- Ziet er prima uit

**Over het actor en interaction diagram**
- Ziet er goed uit
- Misschien handig om ook de attributen van entiteiten vast te leggen? 
- Misschien handig om Data op te splitsen in 2 entiteiten, de ene gaat alleen over platforms, de andere gaat alleen over games. En dan natuurlijk ook een render voor je main/overview en een aparte render entiteit voor je detail view die je bijvoorbeeld GameDetailView kan noemen, met methodes zoals renderGameDetailView etc.
- Dus probeer waar dat kan abstractieniveaus te gebruiken en van het Single Responsibility Principle gebruik te maken. Dit maakt het overzichtelijker tijdens het programmeren, maar ook wanneer je met een team er aan zou werken (anders zitten we allemaal in dezelfde file ook).

**Over de code**
- Ziet er prima uit
- Probeer overal met modules te werken, ook je "script.js" zou je een module kunnen maken
- Je router ziet er prima uit
- Is het verstandiger om met abstractieniveaus te werken (bv in render.js/detail(id)), door het fetchen van de data en het renderen niet in dezelfde functie te schrijven (i.v.m. Single Responsibility Principle)?

**Comment by joostf** [comment]
Goeie tip @ofahchouch-gh!

Door het Single Responsibility Principe toe te passen, maak je je code beter leesbaar en wordt het ook makkelijker om de code uit te breiden!
